version: "3"

services:
  hive-server:
    image: sufar/hive:3.1.3-hadoop3.2.1
    container_name: hive-server
    networks:
        - bigdata
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
  hive-metastore:
    image: sufar/hive:3.1.3-hadoop3.2.1
    container_name: hive-metastore
    networks:
        - bigdata
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9000 datanode:9864 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:3.1.0
    container_name: hive-metastore-postgresql
    networks:
        - bigdata
    ports:
      - "5432:5432"
  # presto-coordinator:
  #   image: shawnzhu/prestodb:0.181
  #   ports:
  #     - "8080:8080"

volumes:
  namenode:
  datanode:

networks:
  bigdata:
    external:
      name: bigdata
